server:
  port: 8030

spring:
  datasource:
    url:  jdbc:mysql://192.168.3.17:3306/mchi?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB   # 单文件最大100MB
      max-request-size: 100MB # 单次请求最大100MB
      file-size-threshold: 2KB # 超过2KB写入临时文件



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null


# RestTemplate配置
rest:
  template:
    connect-timeout: 3000
    read-timeout: 5000

